### ISSUE TITLE
Roll-out ODP / Github meeting minutes to FO project

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-fo#34]
Roll-out ODP / Github meeting minutes to FO project

**Comment by finos-admin** [comment]
Successfully tested indexing and unindexing of attendants via https://github.com/finos/finos-fo/issues/39

Issue template can be tweaked on https://github.com/finos/finos-fo/blob/master/.github/ISSUE_TEMPLATE/Meeting.md

**Comment by maoo** [comment]
This is done.
