### ISSUE TITLE
Clean-up FO Github Teams

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-fo#35]
The 3 Github teams for FO do not represent either the FINOS' revised governance nor the actual historical leaders and participants in the project. 
- https://github.com/orgs/finos/teams/fo-pmc
    - Zero members; the PMC was @donbasuno and @HammadNYC 
- https://github.com/orgs/finos/teams/fo-program
    - @maoo @mcleo-d How is the group intended to be different from the fo-pmc group?
   - Currently Colin, Johan, and Jamie 
- https://github.com/orgs/finos/teams/fo-standards
    - @maoo @mcleo-d, is this intended to be the "FO project" (not the program) team?

The PMC, for now, should be @donbasuno and @HammadNYC. I am not sure why @jbjonesjr is in the FO teams. Ditto @ColinEberhardt. I can't recall either Jamie or Colin being involved in FO. 

@mcleo-d @maoo, Can we delete the PMC group, especially given we have zero people in it and we've done away with programs/PMCs?

Note this will be the first step of clean-up -- there will additional clean up and updates if/as new project leads are chosen.

**Comment by brooklynrob** [comment]
@maoo @mcleo-d Any update on getting these FO project github teams fixed?

**Comment by maoo** [comment]
@brooklynrob - I've unassigned `fo-pmc` and `fo-program` teams from `finos-fo` repo, as they dont apply anymore after FO program disband

Now the only non-FINOS team assigned to the repo is @finos/fo-standards , which includes Colin and Johan.

I also see that Johan and Hammad have direct access to the repo (see screenshot); I'd suggest to get rid of these entitlements and use Teams instead.

<img width="953" alt="Screenshot 2020-08-05 at 10 22 20" src="https://user-images.githubusercontent.com/327285/89389335-90a8a080-d705-11ea-895b-2f9dae37186b.png">


I'll wait for your input to tackle next cleanup steps.
