### ISSUE TITLE
Choose new project leads for FO project

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-fo#36]
Both @HammadNYC and @donbasuno have announced their intention to step down as FO project leads.

By September 2020 or so, we should select new leads for the FO scope, likely concurrent with refining the scope/charter of the project. 

At the July 30, 2020 FO meeting both Daniel Schwartz (Independent) and Stephen Murphy (Genesis) have expressed an interest in being leads.

**Comment by agitana** [comment]
On February 8th, 2021 @ffionwiggins' [stepped forward](https://groups.google.com/a/finos.org/g/community/c/7U3uS0GJ0QQ) to lead the FO project. This proposal has received support from the [FINOS community](https://groups.google.com/a/finos.org/g/community/c/7U3uS0GJ0QQ) and [former FO project leads](https://github.com/finos/finos-fo/issues/38#issuecomment-776905008), and no objections from the community. Therefore @ffionwiggins has been confirmed as the new lead for the FINOS Financial Objects project.

We encourage everyone to engage with the new FO modeling projects: Commodities Payout (commodities-payout@finos.org), and Product Control Common Template (product-control-common-template@finos.org) on the [FO GitHub repository](https://github.com/finos/finos-fo), and to reach out to the project mailing lists with any questions.
