### ISSUE TITLE
Test! - Financial Objects Meeting Minutes

### ISSUE THREAD

**Issue by finos-admin** [finos/finos-fo#39]
## Date
Thursday DD MMM yyyy - 12pm EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- [ ] _Add items here_

## Confluence page
https://finosfoundation.atlassian.net/wiki/spaces/FO/pages/123404294/Financial+Object+Working+Group

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] _Add items here_
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] _Add items here_

## Action Items
- [ ] _Add items here_

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mb412cf99b3a697e8c87e339236f83fbf)
- Meeting Number: 668 814 413
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895
- Recording URL: https://finos.webex.com/mw3300/mywebex/default.do?siteurl=finos&service=1
- Recurrence: Monthly on the 4th Thursday

**Comment by finos-admin** [comment]
present!

**Comment by maoo** [comment]
present!
