### ISSUE TITLE
Jul 30th 2020 - Financial Objects Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/finos-fo#40]
## Date
Jul 30th 2020 - 11am EST

## Untracked attendees
- Johan Sandersson / Factset / @donbasuno 
- Hammad Akbar / Citi / @HammadNYC 
- Nick Kolba / Genesis / @nkolba 
- Stephen Murphy / Genesis
- Will Brown / Genesis
- Ffion Wiggins / Goldman Sachs / @ffionwiggins
- Rich Robinson / Bloomberg / @ rcr203
- Daniel Schwartz / FT Advisory / @dschwartznyc
- Rob Underwood / FINOS / @brooklynrob 
- Aitana Myohl / FINOS / @aitana16 

## Confluence page
- https://finosfoundation.atlassian.net/wiki/spaces/FO/pages/123404294/Financial+Object+Working+Group

## Agenda
- [x] Convene & roll call (5mins)
- [x] Recap of FO project focus over the past couple of years
  - Define agnostic financial object, something that stands alone and can be translated and used in any language, scaled and broadly used. Make financial objects discoverable
  - Goal was _not_ to create a list of financial object libraries for the sake of it, but rather to drive it based on specific use cases, focusing on a solution that's driving some workflow solution or improvement
- [x] Discussion on the future of the FO project
  - some participants highlighted the need to identify a problem before defining a solution
  - problem is that lack of standard data structures means that organizations implement their functionalities in different ways
  - a participant involved with a wide range of use cases proposed to get buy side and sell side firms together and market the FO project as an infra clearinghouse
  - another participant suggested the project focus on translation between these different ways of representing things, instead of developing a new one
  - someone highlighted the close work done between FDC3 and FO: work has been to standardize interfaces to have a common "rosetta stone" layer to connect those identifiers. As that standard matures, it would be useful to have more of those standardized sets of interface data that can be used to connect all those workflows end to end across the desktop. This participant expressed interest in going back to backends and do further work with what's happening within applications
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] @dschwartznyc and Stephen Murphy expressed interest in eventually leading the FO project

## Action Items
- [x] @brooklynrob to draft an RFC to re-visit discussion
  - See https://github.com/finos/finos-fo/issues/38

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mb412cf99b3a697e8c87e339236f83fbf)
- Meeting Number: 668 814 413
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895
- Recording URL: https://finos.webex.com/mw3300/mywebex/default.do?siteurl=finos&service=1
- Recurrence: Monthly on the 4th Thursday

**Comment by RichardWagener365** [comment]
here
