### ISSUE TITLE
Aug 25th 2020 - Financial Objects Meeting Minutes

### ISSUE THREAD

**Issue by aitana16** [finos/finos-fo#41]
## Date
Tuesday Aug 25th 2020 - 11.30am EST

## Untracked attendees
- Ffion Wiggins / GS
- Rich Robinson / Bloomberg
- Minesh Patel / Regnosys
- Azeef Jalaludin 
- Will Brown 

## Agenda
- [x] Convene & roll call (5mins)
- [x] Approve [July 30th](https://github.com/finos/finos-fo/issues/40) meeting minutes - _meeting minutes were approved_
- [x] [RFC: The Future of the Financial Objects project](https://github.com/finos/finos-fo/issues/38)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- **Commodities Reference Data**: 
    - **Reference Data Model**: there was general agreement to move forward with the proposal that the current "_Securities_ Reference Data" project expands its scope to become the "_Reference Data_ project" and that the Commod. Reference Data underlier piece (i.e. the reference data model) moves into that project under its own "Commodity Reference Data" workstream. This [proposal](https://github.com/finos/secref-data/issues/31) has been added to the [agenda](https://github.com/finos/secref-data/issues/28) of the next Securities Reference Data meeting on September 1st for discussion.
    - **Commodity Payout model**: While it will be defined at some point, it was agreed that there is no pressing need to define a "home" for the commodities payout piece produced by the Alloy Pilot Commodities Reference Data working group
- **Financial Objects**: a decision was made to keep the FO project infrastructure (i.e. mailing lists, github repo) open and available to the group for asynchronous collaboration. Recurring meetings will be cancelled and meetings will be scheduled on an ad-hoc basis.all meeting attendees were encouraged to sign up to the Financial Objects project mailing list - which can be done by emailing [fo+subscribe@finos.org](fo+subscribe@finos.org). **All communications relevant to the future and potential scope of the project will be carried out through the [fo@finos.org](fo@finos.org) mailing list and the GitHub issues raised in the Financial Objects GitHub repo (https://github.com/finos/finos-fo/issues).**
- **CDM**: the group will [continue discussing](https://github.com/finos/community/issues/64#issuecomment-680080603) the creation of a FINOS project to continue CDM Extension work after the Alloy Pilot. It was acknowledged that this workstream could potentially move into the Financial Objects projects but will be explored as an independent workstream/ project for now.

## Action Items
- [ ] _Add items here_

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mb412cf99b3a697e8c87e339236f83fbf)
- Meeting Number: 668 814 413
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895
- Recording URL: https://finos.webex.com/mw3300/mywebex/default.do?siteurl=finos&service=1
- Recurrence: Monthly on the 4th Thursday

**Comment by brooklynrob** [comment]
hi

**Comment by ffionwiggins** [comment]
Here

**Comment by toshaellison** [comment]
Present

**Comment by dschwartznyc** [comment]
hi - minutes approved

**Comment by lolabeis** [comment]
here

**Comment by mindthegab** [comment]
Ciao!

**Comment by aitana16** [comment]
hi!

**Comment by TSanborn-ISDA** [comment]
Hi!

**Comment by RichardWagener365** [comment]
hi
