### ISSUE TITLE
11/02/2021 - Commodities Payout Terms Meeting Minutes

### ISSUE THREAD

**Issue by astonGS** [finos/finos-fo#44]
## Date
Thursday, 11/02/2021 - 11am ET / 4pm GMT

## Untracked attendees
- Fullname, Affiliation, GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Group Introductions
- [ ] Brief Recap of CDM Commodities Changes 2020
- [ ] Agree Working Group Target Deliverables

## Discussion Points
- Brief recap of Commodities CDM developments from last year was given. The enhancements to the CDM model are expected to be release in to Rosetta imminently. 
- Current ISDA CDM version in Legend Studio is slightly dated, aim to get model sync update before the next session. 
- Group discussed roadmap items for the working group & agreed that 3 near term topic will be addressed:
  1. Asian Options
  2. Bullet/Vanilla European Options
  3. Option Strategies Representation

## Action Items
- ISDA to give overview of the existing OptionPayout structure at the beginning of the next session which will form platform for identifying enhancements that need to be made to address the 3 topics above. 

### WebEx info
- Meeting link: https://finos.webex.com/finos/j.php?MTID=m67d73e1fc1592e699f3cf95d4627de8d
- Meeting number: 127 391 7484
- Password: JMrsuEmY376
- Call-in: 
    - Join by video system: Dial 1273917484@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number. 
    - Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 391 7484

**Comment by nigelcobb** [comment]
here

**Comment by agitana** [comment]
Hi!

**Comment by TSanborn-ISDA** [comment]
hi

**Comment by iyermakova** [comment]
I am attending the call

**Comment by rvincentISDA** [comment]
On

**Comment by agitana** [comment]
Meeting minutes were approved at the February 18th meeting
