### ISSUE TITLE
fo.finos.org homepage light update

### ISSUE THREAD

**Issue by maoo** [finos/finos-fo#58]
Update fo.finos.org according to the new team composition and initiatives.

Content must be taken from README.md

**Comment by maoo** [comment]
Here's the preview - https://mystifying-swartz-9aa401.netlify.app/ , which is generated from the `new-website` branch (see  https://github.com/finos/finos-fo/pull/70).

There's an issue with the image size and probably other CSS fixes. @grizzwolf , could you please have a look? /CC @agitana

**Comment by agitana** [comment]
hi @maoo looks good to me, thank you

**Comment by toshaellison** [comment]
-I agree the image sizes should be fixed on the home page. 
-It also seems like there should be menu items that link to the work on product control common template and commodities payout and not just the financial objects.
![image](https://user-images.githubusercontent.com/48800847/114405745-d272cc00-9b5b-11eb-889f-cf79317906f5.png)
-Same thing with the left menu once you click on Into.
![image](https://user-images.githubusercontent.com/48800847/114405937-fb935c80-9b5b-11eb-8696-73f82a5b0a59.png)

**Comment by grizzwolf** [comment]
@maoo I cloned the repo, but when I start the website, it is the current version at https://fo.finos.org/ - I'm not sure how to get to the version you're working on currently.

If I run the inspector on the https://mystifying-swartz-9aa401.netlify.app/ page - I see two issues with that one section you're having issues with:

-div class "Block Image" - the flex and max-width sizes are 500px. If you drop both (especially the flex) to 150px, that would correct the desktop version of the site. (however those icons seem to drop off when in the mobile version?).

Code should look like the below - but I'm not sure where to fix that in your version - probably in the custom CSS file? Also - that "Flex" could also be 0 1 150px:

`.imageAlignSide .blockImage {
          flex: > 0 0 150px;
          max-width: 150px;
}`

<img width="1061" alt="Screen Shot 2021-04-13 at 1 12 43 PM" src="https://user-images.githubusercontent.com/873426/114594538-5c558e80-9c5b-11eb-8d5d-bc48b3bcf5ac.png">


- The svg is somehow off it's alignment. I opened it in a new Chrome tab, and looked off - so I opened in Illustrator - screen shot attached. It just needs to be centered and sized. I would imagine Megan would have sent the correct one - but let me know where you're getting the svg from and I can fix if needed. 


<img width="914" alt="Screen Shot 2021-04-13 at 1 12 54 PM" src="https://user-images.githubusercontent.com/873426/114594559-6081ac00-9c5b-11eb-8f23-be8d858d16f9.png">

**Comment by maoo** [comment]
@grizzwolf - uh, my bad! Forgot a tiny yet important detail: i'm working on the `new-website` branch ! 😄 

I've [added your fix](https://github.com/finos/finos-fo/commit/67920093c90ba69c73be71292ebf86c11ddd81a5), and it actually works, see https://mystifying-swartz-9aa401.netlify.app/ .

The SVG is still cut, but it's the same image used by the landscape, so it should be fine. Any idea what's wrong? Worse case, we can export to PNG and use those. WDYT?

**Comment by maoo** [comment]
As discussed with @toshaellison - I removed images for now.

@agitana - the preview is ready to be shared with the FO team: we removed content coming from the previous FO initiative, but more cleanup on the repo must happen. I can work on a PR, but given the board meeting is close, I'd ask if we can merge these website changes today/tomorrow and go live on fo.finos.org.

TY!

**Comment by maoo** [comment]
PR merged - fo.finos.org updated.
