### ISSUE TITLE
05 May 2021 - Product Control Common Template Meeting Minutes

### ISSUE THREAD

**Issue by kenneth-hei** [finos/finos-fo#80]
## Date
Wednesday, May 05 2021 - 9am ET / 2pm BST

## Untracked attendees
- Fullname, Affiliation, GitHub username

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Finalise the required attributes for the Eq option template and discuss the model design for adding the missing attributes in CDM. 

## Minutes of the meeting
- [ ] Approval of the past meeting minutes.
- [ ] Continued discussion on the Eq option sample template including the required attributes to be finalized. 
- [ ] Detailed discussion on the identifier to be used in the common template. 
- [ ] Changed a few attributes to optional given these were not mapped in CDM currently and can be discussed to be added back in the template later once the data transformation logic is finalized.

## Decisions Made
- [ ] NA

## Action Items
- [ ] FINOS to reach out to Refinitiv to initiate discussion on RIC to FIGI mapping in OpenFIGI and the usage of the same for our common template initiative as a submission identifier by the banks who already have pre-approved license of using RICs for their internal pricing.
- [ ] If we get approval from Refinitiv to incorporate its identifier mapping in FIGI, it will help resolve the mapping issues as all mapping would be readily available in FIGI open source API which can be used by banks for their submission. 
- [ ] Participating Banks: As discussed in the meeting, we’re exploring to use openFIGI as the unique identifier in the EqOption common template as FIGI is an open source identifier with mappings across multiple existing identifiers (except RIC, which FINOS is checking on with Refinitiv) which can be retrieved via API. This will entail banks to maintain a mapping between their pricing identifier and openFIGI. Please let us know if you have any concerns relating to the same. 

### WebEx info
•	Meeting link: https://finos.webex.com/finos/j.php?MTID=m87564e9d831b0fbde36f3977b64fb29c
•	Meeting number: 127 143 7803
•	Password: J2SqF2Kp5X2
•	Call-in:
•	Join by video system: Dial 1276424586@finos.webex.com. You can also dial 173.243.2.68 and enter your meeting number.
•	Join by phone: +1-415-655-0003 US Toll | +44-20319-88141 UK Toll | Access code: 127 642 4586

**Comment by RichardWagener365** [comment]
Hi

**Comment by mdemarzio** [comment]
present

**Comment by ashleymercer** [comment]
Attending from Skylight IPV:

@ashleymercer
@NigelHyde
@Adam-McIlroy-Skylight
